config/routes.rb
Omrails::Application.routes.draw do
  resources :qurriculums

  devise_for :users do
    resources :qurriculums
  end

  get 'about' => 'pages#about'

  root :to => 'pages#home'

end

app/models/qurriculum.rb
class Qurriculum < ActiveRecord::Base
  attr_accessible :vacancy

  # Connects qurriculums to their respective user
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  # Connects qurriculums to their respective users. 
  # Destroys dependent qurriculums when user is destroyed
  has_many :qurriculums, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end
end

app/controllers/qurriculums_controller.rb
class QurriculumsController < ApplicationController
  # GET /qurriculums
  # GET /qurriculums.json

  # Authenticate user before they can take actions on qurriculums
  before_filter :authenticate_user!, except: [:index, :show]

  # override layout for the Qurriculum viewers
  layout "viewer", :only => :show


  def index
    # Only show user's own qurriculums in the index
    @qurriculums = current_user.qurriculums.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @qurriculums }
    end
  end

  # GET /qurriculums/1
  # GET /qurriculums/1.json
  def show
    @qurriculum = Qurriculum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @qurriculum }
    end
  end

  # GET /qurriculums/new
  # GET /qurriculums/new.json
  def new
    @qurriculum = current_user.qurriculums.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @qurriculum }
    end
  end

  # GET /qurriculums/1/edit
  def edit
    @qurriculum = current_user.qurriculums.find(params[:id])
  end

  # POST /qurriculums
  # POST /qurriculums.json
  def create
    @qurriculum = current_user.qurriculums.new(params[:qurriculum])

    respond_to do |format|
      if @qurriculum.save
        format.html { redirect_to @qurriculum, notice: 'Qurriculum was successfully created.' }
        format.json { render json: @qurriculum, status: :created, location: @qurriculum }
      else
        format.html { render action: "new" }
        format.json { render json: @qurriculum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /qurriculums/1
  # PUT /qurriculums/1.json
  def update
    @qurriculum = current_user.qurriculums.find(params[:id])

    respond_to do |format|
      if @qurriculum.update_attributes(params[:qurriculum])
        format.html { redirect_to @qurriculum, notice: 'Qurriculum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @qurriculum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qurriculums/1
  # DELETE /qurriculums/1.json
  def destroy
    @qurriculum = current_user.qurriculums.find(params[:id])
    @qurriculum.destroy

    respond_to do |format|
      format.html { redirect_to qurriculums_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/qurriculums_helper.rb
module QurriculumsHelper
end

app/views/layouts/_footer.html.erb
<div class="container">

	<% if user_signed_in? %>
		<div class="footer">
			<small>
				<p>footer paragraph  ; )</p>
			</small>
		</div>
	<% else %>
		<div class="footer">
			<%= link_to "Powered by Qurriculum", root_path, class: "muted" %>
		</div>
	<% end %>

</div>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
    	<div class="row">
  			<div class="span8 offset2">
      		<%= link_to "Qurriculum", root_path, class: "brand" %>
      		<ul class="nav">
        		<li><%= link_to "Home", root_path %></li>
        		<li><%= link_to "About Us", about_path %></li>
        	</ul>
        	<ul class="nav pull-right">
            <li><%= link_to "Account", edit_user_registration_path %></li>	
      		  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      		</ul>
      	</div>
      </div>
    </div>
  </div>
<% else # don't show header, because they visit the qurriculums! %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qurriculum</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	
	<div class="row">
		<div class="span8 offset2">
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
			<% end %>
		</div>
	</div>	

	<%= yield %>


	<%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/viewer.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Qurriculum for (...import company name)</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="background-color:red;">
	<%= render 'layouts/header' %>
	
	<div class="row">
		<div class="span8 offset2">
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
			<% end %>
		</div>
	</div>	

	<%= yield %>


	<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/_dashboard.html.erb
<div id="toparea">
	<div class="container">
		<div style="margin-left:25px;">
			<img src="#" id="logo"/>
			<h1>Dashboard</h1>
		</div>
	</div>
</div>

<div class="container" style="box-shadow: 1px 1px 10px #444;border-radius: 5px;">

	<!-- Qurriculum index area -->
	<div class="row" style="padding:15px 0 50px 0;">
		<div class="span4">
			<button class="btn btn-large btn-primary btn-block" href="#">Create Qurriculum</button>
			
			<div style="margin-top:20px;">
				<button class="btn btn-small" href="#">Edit all Profiles</button>
				<button class="btn btn-small pull-right" href="#"><i class="icon-play-circle" style="margin-right:3px;"></i>Add Video</button>

				<div style="margin-top:20px;">
				<%= link_to "Your Qurriculums", qurriculums_path, class: "btn btn-large btn-block" %>
				</div>
			</div>

		</div>

		<!-- Small 'open' area -->
		<div class="span8">
			<h3>This will be the small marketing / introduction part</h3>
		</div>
		
		<!-- main area -->
		<div class="span8">
			<h3>The main area</h3>
			<p></p>
		</div>

	</div>
</div>

app/views/pages/_landingpage.html.erb
<h1>Welcome to Qurriculum!</h1>
<p>This here will be the landingpage. </br>We will host all sorts of nice HTML here, and a nice Call to Action.</p>
<div class="btn-group">
	<%= link_to "Sign Up Now", new_user_registration_path, class: "btn btn-large btn-success" %>
	<%= link_to "Login", new_user_session_path, class: "btn btn-large"%>
</div>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
	
	<%= render 'dashboard' %>

<% else %>

	<%= render 'landingpage' %>
	
<% end %>

app/views/qurriculums/_form.html.erb
<%= simple_form_for(@qurriculum, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :vacancy %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/qurriculums/edit.html.erb
<h1>Editing qurriculum</h1>

<%= render 'form' %>

<%= link_to 'Show', @qurriculum %> |
<%= link_to 'Back', qurriculums_path %>

app/views/qurriculums/index.html.erb
<h1>Listing qurriculums</h1>

<table>
  <tr>
    <th>Vacancy</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @qurriculums.each do |qurriculum| %>
  <tr>
    <td><%= qurriculum.vacancy %></td>
    <td><%= link_to 'Show', qurriculum %></td>
    <td><%= link_to 'Edit', edit_qurriculum_path(qurriculum) %></td>
    <td><%= link_to 'Destroy', qurriculum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Qurriculum', new_qurriculum_path %>

app/views/qurriculums/new.html.erb
<h1>New qurriculum</h1>

<%= render 'form' %>

<%= link_to 'Back', qurriculums_path %>

app/views/qurriculums/show.html.erb
<div class="container">
	<div id="wrapper">
		
	</div>

	<!-- Tabs area -->
	<div class="tabbable span8">
		<ul class="nav nav-tabs">
      <li class="active"><a href="#tab1" data-toggle="tab">Mijn CV</a></li>
      <li><a href="#tab2" data-toggle="tab">Motivatiebrief</a></li>
	  </ul>
	  <div class="tab-content">
	    <div id="tab1" class="tab-pane active">
	        <p>Content of CV</p>
	    </div>
	    
	    <div id="tab2" class="tab-pane">
				<p>Content of Motivatiebrief</p>
			</div>
		
		</div>
	</div>

	<!-- Personal summary area -->
	<div class="span4">
	</div>

</div>







<p>
  <b>Vacancy:</b>
  <%= @qurriculum.vacancy %>
</p>

<% if current_user == @qurriculum.user %>
	<%= link_to 'Edit', edit_qurriculum_path(@qurriculum) %> |
	<%= link_to 'Back', qurriculums_path %>
<% end %>